// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.color.space.p3.and.uint8
// Description:test getImageData with different seetting from display-p3 canvas
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("test getImageData with different seetting from display-p3 canvas");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

var offscreenCanvas = new OffscreenCanvas(100, 50);
var ctx = offscreenCanvas.getContext('2d', {colorSpace: "display-p3", pixelFormat: "uint8"});

var color_style = 'rgb(50, 100, 150)';
var pixel_expected = [62, 99, 146, 255];
var epsilon = 2;
ctx.fillStyle = color_style;
ctx.fillRect(0, 0, 10, 10);

var pixel = ctx.getImageData(5, 5, 1, 1, {colorSpace: "display-p3", storageFormat: "uint8"}).data;
var passed = true;
_assertSame(pixel.length, pixel_expected.length, "pixel.length", "pixel_expected.length");
for (var i = 0; i < pixel.length; i++)
{
  if (Math.abs(pixel[i] - pixel_expected[i]) > epsilon) {
    passed = false;
  }
}
_assertSame(passed, true, "passed", "true");

pixel_expected = [50, 100, 150, 255];
var pixel = ctx.getImageData(5, 5, 1, 1, {colorSpace: "srgb", storageFormat: "uint8"}).data;
_assertSame(pixel.length, pixel_expected.length, "pixel.length", "pixel_expected.length");
for (var i = 0; i < pixel.length; i++)
{
  if (Math.abs(pixel[i] - pixel_expected[i]) > epsilon) {
    passed = false;
  }
}
_assertSame(passed, true, "passed", "true");
t.done();

});
done();
